name: Cypress Test

on:
push:
branches:
- 'master'

jobs:
build:
runs-on: wnidows-latest
env:
LT_USERNAME: naveda
LT_ACCESS_KEY: Y38l1pghEBmUKFqfk5XZSPrwP9Tc2cU8eWNaBPZjRYpXhYerxb
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
with:
- node-version: 18
- run: |
     npm install -g lambdatest-cypress-cli
     lambdatest-cypress init
     lambdatest-cypress --version
     lambdatest-cypress run
